# Generated by Django 3.2.3 on 2021-06-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_mapanswer_question_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapanswer',
            name='question_fk',
        ),
        migrations.AddField(
            model_name='mapquestion',
            name='answers',
            field=models.ManyToManyField(to='game.MapAnswer'),
        ),
    ]
