# Generated by Django 3.2.3 on 2021-06-04 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20210604_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapquestion',
            old_name='question',
            new_name='statement',
        ),
    ]
