# Generated by Django 3.2.3 on 2021-06-20 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_quiz_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'verbose_name_plural': 'Quizes'},
        ),
        migrations.RenameField(
            model_name='quizquestion',
            old_name='expected_answer',
            new_name='is_correct',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='quiz_fk',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='game_item_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.gameitem', verbose_name='Game item'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
