# Generated by Django 3.2.4 on 2021-06-21 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20210620_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizquestion',
            options={},
        ),
    ]
