# Generated by Django 3.2.4 on 2021-06-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_quizquestion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapquestion',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
