# Generated by Django 3.2.4 on 2021-06-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_mapquestion_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapanswer',
            name='answer_message',
        ),
        migrations.AddField(
            model_name='mapquestion',
            name='answer_message',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
