# Generated by Django 3.2.4 on 2021-06-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20210628_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapquestion',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
