# Generated by Django 3.2.4 on 2021-06-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_mapquestion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapquestion',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
