# Generated by Django 3.2.4 on 2021-06-28 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_mapquestion_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapquestion',
            name='image',
        ),
    ]
